name: TimeTrail
main: com.github.FrozenGamma.TimeTrail.TimeTrail
version: 1.2
permissions:
   TimeTrail.create:
       description: Allows a player to create and destroy TimeTrail tracks.
   TimeTrail.use:
       description: Allows a player to use a TimeTrail track.